### PR TITLE
Use builder-pattern-liked API to improve flexibility of api.Entry (SphU.entry)

### PR DESCRIPTION
**Pull request by gorexlv**
### Does this pull request fix one issue?

Fixes #15 

### Special notes for reviews

### CODE REVIEW

**Comment by louyuting** [comment]
It shows the conflicts. Could you please resolve it?

**Comment by louyuting** [comment]
For a feature, it is best to use one commit log unless necessary.
Could you please refine your commit.
Thanks.

**Comment by louyuting** [comment]
In addition, Could you please remove the ut log file "api/sentinel-record.log" 
Thanks

**Comment by gorexlv** [comment]
> For a feature, it is best to use one commit log unless necessary.
> Could you please refine your commit.
> Thanks.

Agree, sorry for my mistake of ignoring the conflict when RP.  
Fixed it.
Thanks.

**Comment by sczyh30** [comment]
Nice. It could improve the flexibility of `api.Entry(xxx)` and avoid too many "overloaded" functions. Thanks for contributing!

**Pull request merged**
